### ISSUE TITLE
error: File X is too short for prediction

### ISSUE THREAD

**Issue by ya-92** [aldertzomer/RFPlasmid#17]
I keep getting this error when I run RFPlasmd! 
 File X is too short for prediction
any suggestions?

**Comment by aldertzomer** [comment]
Hi
Can you share the file? Is it a fasta file? It's either less than 1000 bp or so, or it is not in the right format.

**Comment by ya-92** [comment]
[ERR349853_SPADES.txt](https://github.com/aldertzomer/RFPlasmid/files/6415205/ERR349853_SPADES.txt)

**Comment by aldertzomer** [comment]
Are you analyzing it in a folder with the extension .txt? or as .fasta ? It won't recognize it when its named .txt.  I just analyzed it using http://klif.uu.nl/rfplasmid/ and it works fine. (results are here: http://klif.uu.nl/rfplasmid/tmp/2021_05_03-1604-11/output/ )

**Comment by ya-92** [comment]
Hi, 
I am analyzing it as .fasta but had to make it .txt so I can upload it here. I also tried using the web interface and it worked. 
I think I have a problem when I use Linux due to CheckM dependencies!
i ran the check and got the following error, even if i already installed prodigal 

checkm test ~/checkm_test_results
[2021-05-03 14:25:43] INFO: CheckM v1.1.3
[2021-05-03 14:25:43] INFO: checkm test /home/y/ya97/checkm_test_results
[2021-05-03 14:25:43] INFO: [CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
[2021-05-03 14:25:43] INFO: [Step 1]: Verifying tree command.
[2021-05-03 14:25:43] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2021-05-03 14:25:43] ERROR: Make sure prodigal is on your system path.

thank you for your response :)

**Comment by aldertzomer** [comment]
Ah that makes sense. Is prodigal in your path? If you have installed CheckM and RFplasmid using Conda, is it in the path of that specific Conda environment?

**Comment by ya-92** [comment]
HI, 
so i reinstalled RFPlasmid in minconda (which is easy enough :) ). I ran the script again and i don't get the prediction output, i get the following error. any suggegstion?
thanks in advance!

(rfplasmid) [ya97@spectre12 out_rf]$ rfplasmid --species Enterobacteriaceae --input ./ --jelly --threads 16 --out ./out_rfplasmid


Start RFPlasmid, version 0.0.16
./out_rfplasmid
copy original contig names
cleanup contig names
start Checkm
    Finished processing 11 of 11 (100.00%) bins.
    Finished parsing hits for 11 of 11 (100.00%) bins.
    Finished processing 11 of 11 (100.00%) bins.
    Finished processing 11 of 11 (100.00%) bins.
    Finished parsing hits for 11 of 11 (100.00%) bins.
Checkm done
start blast plasmiddb
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
blast plasmid genes done
start blast cge
blast cge genes done
count genes per contig done
/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/RFPlasmid/rfplasmid.py:208: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['contig'], df['gene'] = df['contig_gene'].str.split('_', 1).str
count SCMs per contig done
Start kmer count
You have selected kmer-counting with jellyfish
Jellyfish kmer-count done
Count contig length
count contig length ; done
Start merging contig files
Create df_files ; done
Start to add blast output to dataframe
/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/RFPlasmid/rfplasmid.py:362: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df4['genome'], df4['contig'] = df4['source'].str.rsplit('_', 1).str
Traceback (most recent call last):
  File "/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SCM'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/RFPlasmid/rfplasmid.py", line 398, in <module>
    df5b['SCM_genes'] = df5b['SCM']/df5b['genes']
  File "/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'SCM'

**Comment by aldertzomer** [comment]
the diamond search for the single copy chromosomal marker genes failed, that is clear. Can you try to put the fasta files in a folder and the run it like this:

rfplasmid --species Enterobacteriaceae --input folder --jelly --threads 16 --out folder_out

**Comment by ya-92** [comment]
Hi, 
so I tried and named the folder fasta and ran the following command but it gives the same error! 


(rfplasmid) [ya97@spectre12 kp k2_st25]$ rfplasmid --species Enterobacteriaceae --input fasta --jelly --threads 16 --out folder_out


Start RFPlasmid, version 0.0.16
folder_out
copy original contig names
cleanup contig names
start Checkm
    Finished processing 11 of 11 (100.00%) bins.
    Finished parsing hits for 11 of 11 (100.00%) bins.
    Finished processing 11 of 11 (100.00%) bins.
    Finished processing 11 of 11 (100.00%) bins.
    Finished parsing hits for 11 of 11 (100.00%) bins.
Checkm done
start blast plasmiddb
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
Error: Invalid parameter count for option '--max-target-seqs'
blast plasmid genes done
start blast cge
blast cge genes done
count genes per contig done
/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/RFPlasmid/rfplasmid.py:208: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['contig'], df['gene'] = df['contig_gene'].str.split('_', 1).str
count SCMs per contig done
Start kmer count
You have selected kmer-counting with jellyfish
Jellyfish kmer-count done
Count contig length
count contig length ; done
Start merging contig files
Create df_files ; done
Start to add blast output to dataframe
/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/RFPlasmid/rfplasmid.py:362: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df4['genome'], df4['contig'] = df4['source'].str.rsplit('_', 1).str
Traceback (most recent call last):
  File "/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SCM'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/RFPlasmid/rfplasmid.py", line 398, in <module>
    df5b['SCM_genes'] = df5b['SCM']/df5b['genes']
  File "/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/y/ya97/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'SCM'

**Comment by ya-92** [comment]
Hi, 
so I figured out the problem was in the main folder that my fasta files folder was inside! 
it had space in the folder name that I didn't realize was there. once I deleted the space the commands worked just fine!
thanks for your help
