### ISSUE TITLE
Example data set error

### ISSUE THREAD

**Issue by ctparson** [aldertzomer/RFPlasmid#2]
We got everything installed successfully, however when we tried to run the example data set we got the error message pasted below.  Any assistance to correct this would be greatly appreciated. 

(base) fskatlab@KatLab-Linux:~/RFPlasmid$ python3 rfplasmid.py --species Campylobacter --input example --jelly --threads 8 --out output
Python version ok
check if species classification scheme exist
species exist; continue
Start plasmid prediction, version 0.0
output
copy original contig names
cleanup contig names
start Checkm
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/checkm/checkmData.py", line 87, in checkPermissions
    open(self.configFile, 'a')
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/checkm/DATA_CONFIG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 36, in <module>
    from checkm import main
  File "/usr/local/lib/python3.6/dist-packages/checkm/main.py", line 25, in <module>
    from checkm.defaultValues import DefaultValues
  File "/usr/local/lib/python3.6/dist-packages/checkm/defaultValues.py", line 26, in <module>
    class DefaultValues():
  File "/usr/local/lib/python3.6/dist-packages/checkm/defaultValues.py", line 29, in DefaultValues
    __DBM = DBManager()
  File "/usr/local/lib/python3.6/dist-packages/checkm/checkmData.py", line 120, in __init__
    if not self.setRoot():
  File "/usr/local/lib/python3.6/dist-packages/checkm/checkmData.py", line 142, in setRoot
    if not self.config.checkPermissions():
  File "/usr/local/lib/python3.6/dist-packages/checkm/checkmData.py", line 88, in checkPermissions
    except (IOError, e):
NameError: name 'e' is not defined
Checkm done
start blast plasmiddb
blast plasmid genes done
start blast cge
blast cge genes done
count genes per contig done
count SCMs per contig done
Start kmer count
You have selected kmer-counting with jellyfish
Jellyfish kmer-count done
Count contig length
count contig length ; done
Start merging contig files
Create df_files ; done
Traceback (most recent call last):
  File "rfplasmid.py", line 305, in <module>
    df1a = pd.concat(dfList)
  File "/home/fskatlab/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 255, in concat
    sort=sort,
  File "/home/fskatlab/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by aldertzomer** [comment]
Installing checkm needs a bit more effort:

https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm

CheckM relies on a number of precalculated data files which can be downloaded from https://data.ace.uq.edu.au/public/CheckM_databases/. Decompress the file to an appropriate folder and run the following to inform CheckM of where the files have been placed:

> checkm data setRoot <checkm_data_dir>
