### ISSUE TITLE
Merge error

### ISSUE THREAD

**Issue by VMJarocki** [aldertzomer/RFPlasmid#21]
Greetings
I get the following error (installed via conda):

Create df_files ; done
Traceback (most recent call last):
  File "/home/user/Data/miniconda3/envs/rfplasmid/lib/python3.7/site-packages/RFPlasmid/rfplasmid.py", line 346, in <module>
    df1 = pd.merge(df1a, df1b, how='right', left_on=['genome','contig'], right_on=['genome','contig'])
  File "/home/user/Data/miniconda3/envs/rfplasmid/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 120, in merge
    validate=validate,
  File "/home/user/Data/miniconda3/envs/rfplasmid/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 704, in __init__
    self._maybe_coerce_merge_keys()
  File "/home/user/Data/miniconda3/envs/rfplasmid/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1252, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat

Any idea on how to proceed?

**Comment by aldertzomer** [comment]
I think I have been able to replicate the problem. files with multiple "." in them seem to fail because of an improper file name handling step. We will fix this asap
