### ISSUE TITLE
KeyError bug within rfplasmid.py

### ISSUE THREAD

**Issue by rnmitchell** [aldertzomer/RFPlasmid#22]
I encountered this error when running a FASTA file that contained no predicted plasmid genes:
```
Traceback (most recent call last):
  File "/opt/bin/rfplasmid.py", line 385, in <module>
    df5b['SCM_genes'] = df5b['SCM']/df5b['genes']
  File "/opt/conda/envs/rfplasmid/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/conda/envs/rfplasmid/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'SCM'
[Mon Sep 20 20:49:07 2021]
Error in rule rfplasmid:
    jobid: 0
    output: rfplasmid.gff3
    shell:
        rfplasmid.sh genome-tidy.fna taxclass.gff3 rfplasmid.gff3 1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

Going through the code, I noticed there is an error on Line 322- this set of code was evaluating the # of plasmid genes with the ```plasmiddbgenes_per_contig.txt```. However, this line of the code (#322) should be ```df3['plasmid_genes'] = np.NaN```, not ```df3['SCM'] = np.NaN```.  Changing this results in the successful run.

**Comment by LindavdGvB** [comment]
You are right, thanks, we will change it!
