### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by sapuizait** [aldertzomer/RFPlasmid#29]
while trying to run it on a server, i get the error below:

start Checkm
Checkm done
start blast plasmiddb
blast plasmid genes done
start blast cge
blast cge genes done
count genes per contig done
count SCMs per contig done
Start kmer count
Standard kmer-counting method
Kmer count standard method ready
Count contig length
count contig length ; done
Start merging contig files
Create df_files ; done
Traceback (most recent call last):
  File "/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/RFPlasmid/rfplasmid.py", line 340, in <module>
    df1a = pd.concat(dfList)
  File "/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 369, in concat
    op = _Concatenator(
  File "/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 426, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

installed with conda
any ideas?

**Comment by sapuizait** [comment]
oh boy it didnt like .fas, it was resolved when i renamed the input to .fasta
