### ISSUE TITLE
python=3.10 issue with split() function

### ISSUE THREAD

**Issue by aschuerch** [aldertzomer/RFPlasmid#32]
My newest conda environment with rfplasmid pulled python=3.10 which gave me this error:

```

    Finished processing 1 of 1 (100.00%) bins.
    Finished parsing hits for 1 of 1 (100.00%) bins.
    Finished processing 1 of 1 (100.00%) bins.
    Finished processing 1 of 1 (100.00%) bins.
    Finished parsing hits for 1 of 1 (100.00%) bins.
Traceback (most recent call last):
  File "/home/aschuerch/anaconda3/envs/plasmidEC_rfplasmid/lib/python3.10/site-packages/RFPlasmid/rfplasmid.py", line 157, in <module>
    df1['contig'], df1['gene'] = df1['contig_gene'].str.split('_', 1).str
  File "/home/aschuerch/anaconda3/envs/plasmidEC_rfplasmid/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 128, in wrapper
    return func(self, *args, **kwargs)
TypeError: StringMethods.split() takes from 1 to 2 positional arguments but 3 were given
```
A new conda environment with specifically requesting python=3.7 removed the error.

**Comment by aldertzomer** [comment]
@LindavdGvB  do you have an idea? this should work in 3.7 and 3.10

**Comment by aldertzomer** [comment]
We don't get the error with 3.10, but we do get a future warning. Are you using 3.11? Can we get your file that is causing the problem?

**Comment by m-ocejo** [comment]
Dear @aldertzomer ,
I am having the same issue. Installed rfplasmid with conda (today):
 `conda create -n rfplasmid -c conda-forge -c bioconda rfplasmid`
Python version: 3.10.12
`(rfplasmid) segalim@5CD140JTK8:/mnt/c/Users/u0889moc/Documents/PROYECTOS/NETRAM$ python --version
Python 3.10.12`

```
(rfplasmid) segalim@5CD140JTK8:/mnt/c/Users/u0889moc/Documents/PROYECTOS/NETRAM$ rfplasmid --species Campylobacter --input genomes --jelly --threads 8 --out rfplasmid

Start RFPlasmid, version 0.0.18
copy original contig names
cleanup contig names
start Checkm
    Finished processing 103 of 103 (100.00%) bins.
    Finished parsing hits for 103 of 103 (100.00%) bins.
    Finished processing 103 of 103 (100.00%) bins.
    Finished processing 103 of 103 (100.00%) bins.
    Finished parsing hits for 103 of 103 (100.00%) bins.
Checkm done
start blast plasmiddb
Traceback (most recent call last):
  File "/home/segalim/anaconda3/envs/rfplasmid/lib/python3.10/site-packages/RFPlasmid/rfplasmid.py", line 157, in <module>
    df1['contig'], df1['gene'] = df1['contig_gene'].str.split('_', 1).str
  File "/home/segalim/anaconda3/envs/rfplasmid/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 129, in wrapper
    return func(self, *args, **kwargs)
TypeError: StringMethods.split() takes from 1 to 2 positional arguments but 3 were given
```



I tried to upload several genome fasta files to [https://klif.uu.nl/rfplasmid/rfplasmidweb.py](url) and it worked fine.
Please find attached one of the fasta files I use (changed the extension to .txt so I can upload it here):

[NKC1185.txt](https://github.com/aldertzomer/RFPlasmid/files/12260369/NKC1185.txt)

Thank you! :)

**Comment by aldertzomer** [comment]
@LindavdGvB we have an example file now. Shall we check again?

**Comment by m-ocejo** [comment]
Dear Aldert, hope you are doing well. This is just a follow-up message. Have you had a chance to look into it?

Thank you! :)

**Comment by cizydorczyk** [comment]
I get the same error. Any fixes? Downloaded via conda, v0.0.18.

**Comment by anw-sh** [comment]
Faced the same issue, looks like a problem with the version of `python`. 
The following installation with `conda`/`mamba` worked for me.
```bash
$ mamba create -n rfplasmid python=3.7* bioconda::rfplasmid
```

Regards
