### ISSUE TITLE
Error: Database was built with a different version of Diamond and is incompatible

### ISSUE THREAD

**Issue by RoxanaZamudio** [aldertzomer/RFPlasmid#4]
Dear Aldert,
I have an error message below, I was wondering if there is any update of the database. I install the Diamond as you recommended. Please, any advice?
I am using the diamond v0.9.24.125
Many thanks
Roxana

```
~/RFPlasmid$ python3 rfplasmid.py --species Campylobacter --input example --jelly --threads 8 --out output
check if species classification scheme exist
species exist; continue
Start plasmid prediction, version 0.0
output
copy original contig names
cleanup contig names
start Checkm
    Finished processing 4 of 4 (100.00%) bins.
    Finished parsing hits for 4 of 4 (100.00%) bins.
    Finished processing 4 of 4 (100.00%) bins.
    Finished processing 4 of 4 (100.00%) bins.
    Finished parsing hits for 4 of 4 (100.00%) bins.
Checkm done
start blast plasmiddb
Error: Database was built with a different version of Diamond and is incompatible.
Error: Database was built with a different version of Diamond and is incompatible.
Error: Database was built with a different version of Diamond and is incompatible.
Error: Database was built with a different version of Diamond and is incompatible.
rfplasmid.py:122: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df1['contig'], df1['gene'] = df1['contig_gene'].str.split('_', 1).str
Traceback (most recent call last):
  File "rfplasmid.py", line 122, in <module>
    df1['contig'], df1['gene'] = df1['contig_gene'].str.split('_', 1).str
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by aldertzomer** [comment]
Hi Roxana
Yes, common problem. Easily solved though. 

get the databases from:
http://klif.uu.nl/download/plasmid_db/plasmiddb_cge.faa
http://klif.uu.nl/download/plasmid_db/plasmiddb_total.faa

and run
```
diamond makedb --in plasmiddb_cge.faa -d plasmiddb_cge
diamond makedb --in plasmiddb_total.faa -d plasmiddb_total
```

or just remove the old database files and run 
`bash getdb.sh `
in your rfplasmid folder

best wishes
Aldert

**Comment by RoxanaZamudio** [comment]
Hi Aldert, 
Thank you very much. I removed the old database and ran again the `bash getdb.sh` and this is working. However, I have another problem, please see below.

```
~/RFPlasmid$ python3 rfplasmid.py --species Campylobacter --input example --jelly --threads 8 --out output
check if species classification scheme exist
species exist; continue
Start plasmid prediction, version 0.0
output
copy original contig names
cleanup contig names
start Checkm
    Finished processing 4 of 4 (100.00%) bins.
    Finished parsing hits for 4 of 4 (100.00%) bins.
    Finished processing 4 of 4 (100.00%) bins.
    Finished processing 4 of 4 (100.00%) bins.
    Finished parsing hits for 4 of 4 (100.00%) bins.
Checkm done
start blast plasmiddb
rfplasmid.py:122: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df1['contig'], df1['gene'] = df1['contig_gene'].str.split('_', 1).str
blast plasmid genes done
start blast cge
blast cge genes done
count genes per contig done
rfplasmid.py:180: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df['contig'], df['gene'] = df['contig_gene'].str.split('_', 1).str
count SCMs per contig done
Start kmer count
You have selected kmer-counting with jellyfish
Jellyfish kmer-count done
Count contig length
count contig length ; done
Start merging contig files
Create df_files ; done
Start to add blast output to dataframe
Traceback (most recent call last):
  File "rfplasmid.py", line 318, in <module>
    df2 = df2.ix[:-1]
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
```
I am wondering if this error is due to the python version that I am using, which is Python 3.8.1.
Do you have any advice regarding this new issue? should I use a specific python version?
Many thanks again!
Roxana

**Comment by RoxanaZamudio** [comment]
Dear Aldert,
The new script is working. Many thanks for fixing it!
Best,
Roxana
