### ISSUE TITLE
hi! do you know what this error is? 

### ISSUE THREAD

**Issue by Wanli-HE** [aldertzomer/RFPlasmid#5]
Traceback (most recent call last):
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/2442b862/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/2442b862/lib/python3.6/site-packages/checkm/main.py", line 869, in parseOptions
    self.taxonSet(options)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/2442b862/lib/python3.6/site-packages/checkm/main.py", line 240, in taxonSet
    bValidSet = taxonParser.markerSet(options.rank, options.taxon, options.marker_file)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/2442b862/lib/python3.6/site-packages/checkm/taxonParser.py", line 82, in markerSet
    taxonMarkerSets = self.readMarkerSets()
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/2442b862/lib/python3.6/site-packages/checkm/taxonParser.py", line 40, in readMarkerSets
    for line in open(DefaultValues.TAXON_MARKER_SETS):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/home/hsv709/.checkm/taxon_marker_sets.tsv'
Traceback (most recent call last):
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/rfplasmid/rfplasmid.py", line 305, in <module>
    df1a = pd.concat(dfList)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/2442b862/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/2442b862/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by aldertzomer** [comment]
I think you have not configured checkm or downloaded the data files. See https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm

**Comment by Wanli-HE** [comment]
thanks for your answer!

but i still meet a problem, using the v 0.3.

Traceback (most recent call last):
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/rfplasmid/rfplasmid.py", line 305, in <module>
    df1a = pd.concat(dfList)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/d7770109/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/d7770109/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by aldertzomer** [comment]
I'm not sure what the version 0.3 is. rfplasmid is currently at version 0.09 (in pip).   Is this with the latest version?
